export const GET_PHASES_LIST = 'GET_PHASES_LIST'
export const GET_PHASES_LIST_SUCCESS = 'GET_PHASES_LIST_SUCCESS'
export const GET_PHASES_LIST_FAILURE = 'GET_PHASES_LIST_FAILURE'

// export const GET_PHASES_LIST = 'GET_PHASES_LIST'
// export const GET_PHASES_LIST_SUCCESS = 'GET_PHASES_LIST_SUCCESS'
// export const GET_PHASES_LIST_FAILURE = 'GET_PHASES_LIST_FAILURE'